# Generated by Django 4.2.15 on 2024-08-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
